DEFAULT_CAMERA_INDEX = 0
DEFAULT_TARGET_FPS = 30
DEFAULT_FRAME_WIDTH = 1280
DEFAULT_FRAME_HEIGHT = 960
# Zero means run without an automatic frame-count stop condition.
DEFAULT_MAX_FRAMES = 0
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.5
DEFAULT_MIN_TRACKING_CONFIDENCE = 0.5
DEFAULT_MODEL_COMPLEXITY = 1

GESTURE_DEFAULT_HAND_ID = "hand-1"
GESTURE_MODEL_RELATIVE_PATH = "models/hand_landmarker.task"
GESTURE_DETECT_MAX_SIDE = 640
GESTURE_MOTION_PRESET = "medium"

# Emit one summary log for every N processed gesture packets.
GESTURE_FRAME_SUMMARY_INTERVAL = 30
DEBUG_FPS_SAMPLE_WINDOW = 10

# Hand-scale heuristic depth estimation tuning.
DEPTH_ESTIMATION_NEAR_HAND_SCALE = 0.55
DEPTH_ESTIMATION_FAR_HAND_SCALE = 0.18
DEPTH_ESTIMATION_LOCAL_Z_WEIGHT = 0.35

# Keep tracking in a temporary-loss state for this many consecutive missing frames.
TEMPORAL_TRACKING_TEMPORARY_LOSS_FRAMES = 6

# Reducer tuning defaults for blur/fallback stability while keeping low latency.
ENTER_THRESHOLD = 0.62
RELEASE_THRESHOLD = 0.42
PINCH_CONFIRM_FRAMES = 4
RELEASE_CONFIRM_FRAMES = 4
RELAXED_RELEASE_CONFIRM_FRAMES = 2
PINCH_MIN_HOLD_FRAMES = 1
GRACE_FRAMES = 6
FALLBACK_MAX_FRAMES = 8
REACQUIRE_BLEND_FRAMES = 4
REACQUIRE_GATE_DISTANCE = 0.16
REACQUIRE_MAX_DX = 0.06
REACQUIRE_MAX_DY = 0.05
OPEN_MARGIN_MIN = 0.10
RELAXED_OPEN_MARGIN_MIN = 0.05
LOW_QUALITY_CONFIDENCE = 0.60
RELAXED_QUALITY_CONFIDENCE = 0.45
HIGH_BLUR_LEVEL = 0.62

# Motion-response shaping for blur-aware smoothing.
MOTION_ALPHA_X_MULTIPLIER = 0.70
MOTION_ALPHA_X_FLOOR = 0.05
MOTION_ALPHA_Y_OFFSET = 0.04
MOTION_ALPHA_Y_MAX = 0.92
LOW_QUALITY_MOTION_ALPHA_Y_MULTIPLIER = 0.55
LOW_QUALITY_MOTION_ALPHA_Y_FLOOR = 0.30
HIGH_MOTION_ALPHA_Y_FLOOR = 0.55
LATERAL_BLUR_X_GATE_MULTIPLIER = 4.0
LATERAL_BLUR_Y_DELTA_BLEND = 0.40

# Equivalent XYZ rotation channel tuning.
# Use cyclic slots per axis; more slots gives smoother feel.
ROT_SLOT_COUNT = 24
ROT_SLOT_STEP_DEG = 360.0 / ROT_SLOT_COUNT
ROT_EQ_GAIN_X = 220.0
ROT_EQ_GAIN_Y = 220.0
ROT_EQ_GAIN_Z = 260.0
ROT_EQ_DEADZONE_X = 0.006
ROT_EQ_DEADZONE_Y = 0.006
ROT_EQ_DEADZONE_Z = 0.005
ROT_EQ_ACTIVE_MIN_DEG = 0.9
ROT_GATE_FRAMES = 3
ROT_GATE_RELEASE_FRAMES = 1
ROT_DELTA_CLAMP_DEG = 14.0
ROT_DELTA_NOISE_DEG = 0.08
ROT_OPPOSITE_JITTER_SUPPRESS_DEG = 1.2
ROT_TREND_MIN_DEG = 0.6
ROT_CONTINUOUS_DELTA_ALPHA = 0.40
ROT_DOMINANT_AXIS_RATIO = 1.75
ROT_SECONDARY_AXIS_ATTENUATION = 0.12
ROT_MODE_GRAB_MIN_FRAMES = 3
ROT_MODE_OPEN_MIN_FRAMES = 2
ROT_MODE_TIMEOUT_FRAMES = 36
ROT_MODE_TOGGLE_COOLDOWN_MS = 3000
ROT_HAND_GRAB_TIP_SPREAD_MAX = 0.27
ROT_HAND_GRAB_TIP_WRIST_MAX = 0.30

# Pinch stability guards for motion/front-facing robustness.
PINCH_RELEASE_BLOCK_WRIST_SPEED = 4.0
PINCH_RELEASE_MIN_QUALITY_WHEN_STABLE = 0.58

__all__ = [
    "DEBUG_FPS_SAMPLE_WINDOW",
    "DEFAULT_CAMERA_INDEX",
    "DEFAULT_FRAME_HEIGHT",
    "DEFAULT_FRAME_WIDTH",
    "DEFAULT_MAX_FRAMES",
    "DEFAULT_MIN_DETECTION_CONFIDENCE",
    "DEFAULT_MIN_TRACKING_CONFIDENCE",
    "DEFAULT_MODEL_COMPLEXITY",
    "DEFAULT_TARGET_FPS",
    "DEPTH_ESTIMATION_FAR_HAND_SCALE",
    "DEPTH_ESTIMATION_LOCAL_Z_WEIGHT",
    "DEPTH_ESTIMATION_NEAR_HAND_SCALE",
    "ENTER_THRESHOLD",
    "FALLBACK_MAX_FRAMES",
    "GESTURE_DEFAULT_HAND_ID",
    "GESTURE_DETECT_MAX_SIDE",
    "GESTURE_FRAME_SUMMARY_INTERVAL",
    "GESTURE_MOTION_PRESET",
    "GESTURE_MODEL_RELATIVE_PATH",
    "GRACE_FRAMES",
    "HIGH_BLUR_LEVEL",
    "HIGH_MOTION_ALPHA_Y_FLOOR",
    "LATERAL_BLUR_X_GATE_MULTIPLIER",
    "LATERAL_BLUR_Y_DELTA_BLEND",
    "LOW_QUALITY_CONFIDENCE",
    "LOW_QUALITY_MOTION_ALPHA_Y_FLOOR",
    "LOW_QUALITY_MOTION_ALPHA_Y_MULTIPLIER",
    "MOTION_ALPHA_X_FLOOR",
    "MOTION_ALPHA_X_MULTIPLIER",
    "MOTION_ALPHA_Y_MAX",
    "MOTION_ALPHA_Y_OFFSET",
    "OPEN_MARGIN_MIN",
    "PINCH_CONFIRM_FRAMES",
    "PINCH_MIN_HOLD_FRAMES",
    "PINCH_RELEASE_BLOCK_WRIST_SPEED",
    "PINCH_RELEASE_MIN_QUALITY_WHEN_STABLE",
    "REACQUIRE_BLEND_FRAMES",
    "REACQUIRE_GATE_DISTANCE",
    "REACQUIRE_MAX_DX",
    "REACQUIRE_MAX_DY",
    "RELAXED_OPEN_MARGIN_MIN",
    "RELAXED_QUALITY_CONFIDENCE",
    "RELAXED_RELEASE_CONFIRM_FRAMES",
    "ROT_EQ_GAIN_X",
    "ROT_EQ_GAIN_Y",
    "ROT_EQ_GAIN_Z",
    "ROT_EQ_DEADZONE_X",
    "ROT_EQ_DEADZONE_Y",
    "ROT_EQ_DEADZONE_Z",
    "ROT_EQ_ACTIVE_MIN_DEG",
    "ROT_GATE_FRAMES",
    "ROT_GATE_RELEASE_FRAMES",
    "ROT_DELTA_CLAMP_DEG",
    "ROT_DELTA_NOISE_DEG",
    "ROT_CONTINUOUS_DELTA_ALPHA",
    "ROT_DOMINANT_AXIS_RATIO",
    "ROT_OPPOSITE_JITTER_SUPPRESS_DEG",
    "ROT_SLOT_COUNT",
    "ROT_SLOT_STEP_DEG",
    "ROT_SECONDARY_AXIS_ATTENUATION",
    "ROT_MODE_GRAB_MIN_FRAMES",
    "ROT_MODE_OPEN_MIN_FRAMES",
    "ROT_MODE_TIMEOUT_FRAMES",
    "ROT_MODE_TOGGLE_COOLDOWN_MS",
    "ROT_HAND_GRAB_TIP_SPREAD_MAX",
    "ROT_HAND_GRAB_TIP_WRIST_MAX",
    "ROT_TREND_MIN_DEG",
    "RELEASE_CONFIRM_FRAMES",
    "RELEASE_THRESHOLD",
    "TEMPORAL_TRACKING_TEMPORARY_LOSS_FRAMES",
]
