DEFAULT_CAMERA_INDEX = 0
DEFAULT_TARGET_FPS = 30
DEFAULT_FRAME_WIDTH = 1280
DEFAULT_FRAME_HEIGHT = 960
# Zero means run without an automatic frame-count stop condition.
DEFAULT_MAX_FRAMES = 0
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.5
DEFAULT_MIN_TRACKING_CONFIDENCE = 0.5
DEFAULT_MODEL_COMPLEXITY = 1

GESTURE_DEFAULT_HAND_ID = "hand-1"
GESTURE_MODEL_RELATIVE_PATH = "models/hand_landmarker.task"
GESTURE_DETECT_MAX_SIDE = 640
GESTURE_MOTION_PRESET = "medium"

# Emit one summary log for every N processed gesture packets.
GESTURE_FRAME_SUMMARY_INTERVAL = 30
DEBUG_FPS_SAMPLE_WINDOW = 10

# Hand-scale heuristic depth estimation tuning.
DEPTH_ESTIMATION_NEAR_HAND_SCALE = 0.55
DEPTH_ESTIMATION_FAR_HAND_SCALE = 0.18
DEPTH_ESTIMATION_LOCAL_Z_WEIGHT = 0.35

# Keep tracking in a temporary-loss state for this many consecutive missing frames.
TEMPORAL_TRACKING_TEMPORARY_LOSS_FRAMES = 6

# Reducer tuning defaults for blur/fallback stability while keeping low latency.
ENTER_THRESHOLD = 0.62
RELEASE_THRESHOLD = 0.42
PINCH_CONFIRM_FRAMES = 4
RELEASE_CONFIRM_FRAMES = 4
RELAXED_RELEASE_CONFIRM_FRAMES = 2
PINCH_MIN_HOLD_FRAMES = 1
GRACE_FRAMES = 6
FALLBACK_MAX_FRAMES = 8
REACQUIRE_BLEND_FRAMES = 4
REACQUIRE_GATE_DISTANCE = 0.16
REACQUIRE_MAX_DX = 0.06
REACQUIRE_MAX_DY = 0.05
OPEN_MARGIN_MIN = 0.10
RELAXED_OPEN_MARGIN_MIN = 0.05
LOW_QUALITY_CONFIDENCE = 0.60
RELAXED_QUALITY_CONFIDENCE = 0.45
HIGH_BLUR_LEVEL = 0.62

# Motion-response shaping for blur-aware smoothing.
MOTION_ALPHA_X_MULTIPLIER = 0.70
MOTION_ALPHA_X_FLOOR = 0.05
MOTION_ALPHA_Y_OFFSET = 0.04
MOTION_ALPHA_Y_MAX = 0.92
LOW_QUALITY_MOTION_ALPHA_Y_MULTIPLIER = 0.55
LOW_QUALITY_MOTION_ALPHA_Y_FLOOR = 0.30
HIGH_MOTION_ALPHA_Y_FLOOR = 0.55
LATERAL_BLUR_X_GATE_MULTIPLIER = 4.0
LATERAL_BLUR_Y_DELTA_BLEND = 0.40

__all__ = [
    "DEBUG_FPS_SAMPLE_WINDOW",
    "DEFAULT_CAMERA_INDEX",
    "DEFAULT_FRAME_HEIGHT",
    "DEFAULT_FRAME_WIDTH",
    "DEFAULT_MAX_FRAMES",
    "DEFAULT_MIN_DETECTION_CONFIDENCE",
    "DEFAULT_MIN_TRACKING_CONFIDENCE",
    "DEFAULT_MODEL_COMPLEXITY",
    "DEFAULT_TARGET_FPS",
    "DEPTH_ESTIMATION_FAR_HAND_SCALE",
    "DEPTH_ESTIMATION_LOCAL_Z_WEIGHT",
    "DEPTH_ESTIMATION_NEAR_HAND_SCALE",
    "ENTER_THRESHOLD",
    "FALLBACK_MAX_FRAMES",
    "GESTURE_DEFAULT_HAND_ID",
    "GESTURE_DETECT_MAX_SIDE",
    "GESTURE_FRAME_SUMMARY_INTERVAL",
    "GESTURE_MOTION_PRESET",
    "GESTURE_MODEL_RELATIVE_PATH",
    "GRACE_FRAMES",
    "HIGH_BLUR_LEVEL",
    "HIGH_MOTION_ALPHA_Y_FLOOR",
    "LATERAL_BLUR_X_GATE_MULTIPLIER",
    "LATERAL_BLUR_Y_DELTA_BLEND",
    "LOW_QUALITY_CONFIDENCE",
    "LOW_QUALITY_MOTION_ALPHA_Y_FLOOR",
    "LOW_QUALITY_MOTION_ALPHA_Y_MULTIPLIER",
    "MOTION_ALPHA_X_FLOOR",
    "MOTION_ALPHA_X_MULTIPLIER",
    "MOTION_ALPHA_Y_MAX",
    "MOTION_ALPHA_Y_OFFSET",
    "OPEN_MARGIN_MIN",
    "PINCH_CONFIRM_FRAMES",
    "PINCH_MIN_HOLD_FRAMES",
    "REACQUIRE_BLEND_FRAMES",
    "REACQUIRE_GATE_DISTANCE",
    "REACQUIRE_MAX_DX",
    "REACQUIRE_MAX_DY",
    "RELAXED_OPEN_MARGIN_MIN",
    "RELAXED_QUALITY_CONFIDENCE",
    "RELAXED_RELEASE_CONFIRM_FRAMES",
    "RELEASE_CONFIRM_FRAMES",
    "RELEASE_THRESHOLD",
    "TEMPORAL_TRACKING_TEMPORARY_LOSS_FRAMES",
]