DEFAULT_CAMERA_INDEX = 0
DEFAULT_TARGET_FPS = 30
DEFAULT_FRAME_WIDTH = 1280
DEFAULT_FRAME_HEIGHT = 960
# Zero means run without an automatic frame-count stop condition.
DEFAULT_MAX_FRAMES = 0
DEFAULT_MIN_DETECTION_CONFIDENCE = 0.5
DEFAULT_MIN_TRACKING_CONFIDENCE = 0.5
DEFAULT_MODEL_COMPLEXITY = 1

# Emit one summary log for every N processed gesture packets.
GESTURE_FRAME_SUMMARY_INTERVAL = 30
BRIDGE_HEARTBEAT_INTERVAL_FRAMES = 30
BRIDGE_MIN_TRACKING_CONFIDENCE = 0.6

MAX_ERROR_HISTORY = 10
RENDER_POSE_LOG_DEBOUNCE_MS = 500
DEBUG_FPS_SAMPLE_WINDOW = 10

# Keep tracking in a temporary-loss state for this many consecutive missing frames.
TEMPORAL_TRACKING_TEMPORARY_LOSS_FRAMES = 8
TEMPORAL_PINCH_ENTER_THRESHOLD = 0.10
TEMPORAL_PINCH_HOLD_THRESHOLD = 0.06
TEMPORAL_PINCH_RELEASE_THRESHOLD = 0.12
# Require this many consecutive frames before promoting a pinch candidate to confirmed pinched.
TEMPORAL_PINCH_CONFIRM_FRAMES = 5
# Require this many consecutive frames before promoting a release candidate to confirmed open.
TEMPORAL_RELEASE_CONFIRM_FRAMES = 5
TEMPORAL_SMOOTHING_ALPHA = 0.42
TEMPORAL_XY_SMOOTHING_ALPHA = 0.18
TEMPORAL_POSITION_DEADZONE = 0.025
TEMPORAL_PREDICTION_BLEND = 0.40
TEMPORAL_PREDICTION_LEAD = 0.85
TEMPORAL_LOST_TRACKING_MOTION_DAMPING = 0.72

# Hand-scale heuristic depth estimation tuning.
DEPTH_ESTIMATION_NEAR_HAND_SCALE = 0.55
DEPTH_ESTIMATION_FAR_HAND_SCALE = 0.18
DEPTH_ESTIMATION_LOCAL_Z_WEIGHT = 0.35